export const data = [
  {
    id: "1",
    cover: "/banner.jpg",
    profile: "/profile.jpg",
    name: "Medi Kingura",
    address: "Kinshasa, RDC",
    email: "medikingura86@gmail.com",
    phone: "+243 991 795 930",
    facebook: "https://link",
    instagram: "https://link",
    linkedin: "https://link",
    whatsapp: "https://link",
  },
  {
    id: "2",
    cover: "/banner.jpg",
    profile: "/profile.jpg",
    name: "Plamedie Kingura",
    address: "Kinshasa, RDC",
    email: "israellakingura@gmail.com",
    phone: "+243 999 999 999",
    facebook: "https://link",
    instagram: "https://link",
    linkedin: "https://link",
    whatsapp: "https://link",
  },
  {
    id: "3",
    cover: "/banner.jpg",
    profile: "/profile.jpg",
    name: "Joseph Mulumba",
    address: "Kinshasa, RDC",
    email: "lepropulseur@gmail.com",
    phone: "+243 999 999 999",
    facebook: "https://link",
    instagram: "https://link",
    linkedin: "https://link",
    whatsapp: "https://link",
  },
];
